# ============================================================
# KUBERNETES DEPLOYMENT FILES FOR PIAZZA API
# ============================================================
# Save each section to its own file in a k8s/ folder
# Then run: ./deploy.sh
# ============================================================

# ============================================================
# FILE: k8s/deployment.yaml
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-api
  labels:
    app: piazza-api
spec:
  replicas: 5  # Required: 5 replicas
  selector:
    matchLabels:
      app: piazza-api
  template:
    metadata:
      labels:
        app: piazza-api
    spec:
      containers:
      - name: piazza-api
        image: YOUR_DOCKERHUB_USERNAME/piazza-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: piazza-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: piazza-secrets
              key: jwt-secret
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5


# ============================================================
# FILE: k8s/service.yaml
# ============================================================
# Piazza API LoadBalancer Service
# Exposes the API via Google Cloud Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: piazza-api-service
  labels:
    app: piazza-api
spec:
  type: LoadBalancer  # Creates external load balancer on GCP
  ports:
  - port: 80          # External port
    targetPort: 3000  # Container port
    protocol: TCP
    name: http
  selector:
    app: piazza-api


# ============================================================
# FILE: k8s/secrets.yaml
# ============================================================
# Piazza API Secrets
# IMPORTANT: Replace base64 values before deploying
# Encode: echo -n "your-value" | base64
apiVersion: v1
kind: Secret
metadata:
  name: piazza-secrets
type: Opaque
data:
  # echo -n "mongodb://mongo:27017/piazza" | base64
  mongodb-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L3BpYXp6YQ==
  # echo -n "your-super-secret-jwt-key" | base64
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==


# ============================================================
# FILE: k8s/mongodb.yaml
# ============================================================
# MongoDB StatefulSet for Kubernetes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
# MongoDB Service (internal)
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
  clusterIP: None


# ============================================================
# FILE: k8s/deploy.sh
# ============================================================
#!/bin/bash
# Piazza API Kubernetes Deployment Script

echo "=========================================="
echo "  Piazza API - Kubernetes Deployment"
echo "=========================================="

# Step 1: Create secrets
echo "\n[1/4] Creating secrets..."
kubectl apply -f secrets.yaml

# Step 2: Deploy MongoDB
echo "\n[2/4] Deploying MongoDB..."
kubectl apply -f mongodb.yaml
kubectl wait --for=condition=ready pod -l app=mongo --timeout=120s

# Step 3: Deploy Piazza API (5 replicas)
echo "\n[3/4] Deploying Piazza API..."
kubectl apply -f deployment.yaml

# Step 4: Create LoadBalancer
echo "\n[4/4] Creating LoadBalancer..."
kubectl apply -f service.yaml

# Wait for external IP
echo "\nWaiting for external IP..."
while true; do
  EXTERNAL_IP=$(kubectl get service piazza-api-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  if [ -n "$EXTERNAL_IP" ]; then break; fi
  echo "  Still waiting..."
  sleep 10
done

echo "\n=========================================="
echo "  DEPLOYMENT COMPLETE!"
echo "  External IP: $EXTERNAL_IP"
echo "  API URL: http://$EXTERNAL_IP"
echo "=========================================="

kubectl get pods -l app=piazza-api

